[package]
name = "ukechug"
version = "0.1.0"
edition = "2021"

[dependencies]
html5ever = "0.27"
cssparser = "0.33"
url = "2.5"
image = "0.25"
imageproc = "0.25"
ab_glyph = "0.2"
clap = { version = "4.0", features = ["derive"] }